#!/bin/bash
set -e

export PATH="$HOME/.local/bin:$PATH"

if test ! "$(which ansible)"; then
  echo "Installing ansible..."
  sudo apt-get install python2.7 python-pip python-apt
  pip install --upgrade --user pip
  pip install --user ansible===2.3.2.0 jinja2==2.8.1 ansible-lint
fi

python --version
ansible --version
ansible-galaxy -r requirements.yml install
ansible-playbook main.yml -D
