#!/bin/bash
set -e

if test ! "$(which ansible)"; then
  echo "Installing ansible..."
  sudo apt-get install python2.7 python-pip python-apt
  sudo -H pip install ansible===2.3.2.0 ansible-lint
fi

python --version
ansible --version
ansible-galaxy -r requirements.yml install
ansible-playbook main.yml -D
