- name: Add node apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add node repositories
  apt_repository: repo='{{ item }} https://deb.nodesource.com/node_{{ node_version }}.x xenial main'
  with_items:
    - deb
    - deb-src

- name: Install Node
  package: name=nodejs
