- name: Add Skype apt keys
  apt_key: url=https://repo.skype.com/data/SKYPE-GPG-KEY

- name: Add Skype repository
  apt_repository: repo='deb [arch=amd64] https://repo.skype.com/deb stable main' filename=skype-stable

- name: Install Skype
  package: name=skypeforlinux
