- name: Check if Telegram is installed
  stat:
    path: ~/.local/share/Telegram/Telegram
  register: telegram_binary
  become: false

- name: Download Telegram package
  get_url:
    url: https://tdesktop.com/linux
    dest: /tmp/telegram.tar.xz
  when:
    - telegram_binary.stat.isreg is not defined or telegram_binary.stat.isreg == false

- name: Ensure needed dirs exists
  file:
    path: "{{item}}"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0755
  with_items:
    - ~/.local/share
    - ~/bin
  become: false

- name: Unpack Telegram
  unarchive:
    src: /tmp/telegram.tar.xz
    dest: ~/.local/share
  when:
    - telegram_binary.stat.isreg is not defined or telegram_binary.stat.isreg == false
  become: false

- name: Install Telegram
  file:
    src: ~/.local/share/Telegram/Telegram
    dest: ~/bin/telegram
    state: link
  when:
    - telegram_binary.stat.isreg is not defined or telegram_binary.stat.isreg == false
  become: false

- name: Remove Telegram package
  file:
    path: /tmp/telegram.tar.xz
    state: absent
  when:
    - telegram_binary.stat.isreg is not defined or telegram_binary.stat.isreg == false
