- name: Check Telegram is installed
  stat:
    path: /home/{{user}}/.local/share/Telegram
  register: telegram_binary

- name: Download Telegram package
  get_url:
    url: https://tdesktop.com/linux
    dest: /tmp/telegram.tar.xz
  when:
    - telegram_binary.stat.isreg is defined and telegram_binary.stat.isreg == false

- name: Ensure ~/.local/share exists
  file:
    path: /home/{{user}}/.local/share
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0755

- name: Unpack Telegram
  unarchive:
    src: /tmp/telegram.tar.xz
    dest: /home/{{user}}/.local/share
  when:
    - telegram_binary.stat.isreg is defined and telegram_binary.stat.isreg == false
  become: false

- name: Install Telegram
  file:
    src: /home/{{user}}/.local/share/Telegram/Telegram
    dest: /home/{{user}}/bin/telegram
    state: link
  when:
    - telegram_binary.stat.isreg is defined and telegram_binary.stat.isreg == false
  become: false

- name: Remove Telegram package
  file:
    path: /tmp/telegram.tar.xz
    state: absent
  when:
    - telegram_binary.stat.isreg is defined and telegram_binary.stat.isreg == false
